name = "Simple Gists"
license = "MIT"
licenselink = "https://github.com/dmachard/hugo-theme-gists/blob/master/LICENSE"
description = "gists hugo theme"
homepage = "https://github.com/dmachard/hugo-theme-gists/"
tags = ["blog", "gists" ]
features = []

[author]
  name = "Denis Machard"
  homepage = "https://github.com/dmachard/hugo-theme-gists/"
