name = "Gists"
license = "MIT"
licenselink = "https://github.com/dmachard/hugo-theme-gists/blob/master/LICENSE"
description = "A gists hugo theme"

homepage = "https://github.com/dmachard/hugo-theme-gists/"

demosite = "https://dmachard.github.io/"

tags = [
  "blog",
  "gists", 
  "minimalist" 
]
features = [
  "blog",
  "pinned",
  "tags"
]

[author]
  name = "Denis Machard"
  homepage = "https://github.com/dmachard/"
